apiVersion: v1
kind: Service
metadata:
  name: <the-app-name>
spec:
  type: LoadBalancer # Change the service in case of different needs
  selector:
    app: <the-app-name>
  ports:
  - port: <Port>
    targetPort: <Target Port>
